/* Generated by re2j 0.13.6.dev on Mon Jul 27 17:41:42 2009 */
package org.yecht;

// Equivalent to implicit.re
public class ImplicitScanner {
    // syck_type_id_to_uri
    public static String typeIdToUri(String type_id) {
//        System.err.println("typeIdToUri(" + type_id + ")");
        byte[] data = null;
        try {
          data = type_id.getBytes("ISO8859-1");
        } catch(Exception e) {}
        byte[] dx = new byte[data.length+1];
        System.arraycopy(data, 0, dx, 0, data.length);
        dx[data.length] = 0;
        data = dx;
        int cursor = 0;
        int limit = data.length;
        int marker = -1;

        int gotoPoint = -1;
        byte yych = (byte) 0;
        gotoNext: while(gotoPoint != -2) {
            int currentGoto = gotoPoint; gotoPoint = -2;
            switch(currentGoto) {
            case -1: 

                yych = data[cursor];
                switch (yych) {
                case 0x00:    {gotoPoint = 2; continue gotoNext;}
                case '!':    {gotoPoint = 6; continue gotoNext;}
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                case 'A':
                case 'B':
                case 'C':
                case 'D':
                case 'E':
                case 'F':
                case 'G':
                case 'H':
                case 'I':
                case 'J':
                case 'K':
                case 'L':
                case 'M':
                case 'N':
                case 'O':
                case 'P':
                case 'Q':
                case 'R':
                case 'S':
                case 'T':
                case 'U':
                case 'V':
                case 'W':
                case 'X':
                case 'Y':
                case 'Z':
                case '_':
                case 'a':
                case 'b':
                case 'c':
                case 'd':
                case 'e':
                case 'f':
                case 'g':
                case 'h':
                case 'i':
                case 'j':
                case 'k':
                case 'l':
                case 'm':
                case 'n':
                case 'o':
                case 'p':
                case 'q':
                case 'r':
                case 's':
                case 'u':
                case 'v':
                case 'w':
                case 'y':
                case 'z':    {gotoPoint = 8; continue gotoNext;}
                case 't':    {gotoPoint = 3; continue gotoNext;}
                case 'x':    {gotoPoint = 5; continue gotoNext;}
                default:    {gotoPoint = 9; continue gotoNext;}
                }
            case 2:
                cursor = marker;
                {gotoPoint = 4; continue gotoNext;}
            case 3:
                yych = data[(marker = ++cursor)];
                switch (yych) {
                case ',':    {gotoPoint = 14; continue gotoNext;}
                case '-':    {gotoPoint = 10; continue gotoNext;}
                case '.':    {gotoPoint = 15; continue gotoNext;}
                case '/':    {gotoPoint = 16; continue gotoNext;}
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                case 'A':
                case 'B':
                case 'C':
                case 'D':
                case 'E':
                case 'F':
                case 'G':
                case 'H':
                case 'I':
                case 'J':
                case 'K':
                case 'L':
                case 'M':
                case 'N':
                case 'O':
                case 'P':
                case 'Q':
                case 'R':
                case 'S':
                case 'T':
                case 'U':
                case 'V':
                case 'W':
                case 'X':
                case 'Y':
                case 'Z':
                case '_':
                case 'b':
                case 'c':
                case 'd':
                case 'e':
                case 'f':
                case 'g':
                case 'h':
                case 'i':
                case 'j':
                case 'k':
                case 'l':
                case 'm':
                case 'n':
                case 'o':
                case 'p':
                case 'q':
                case 'r':
                case 's':
                case 't':
                case 'u':
                case 'v':
                case 'w':
                case 'x':
                case 'y':
                case 'z':    {gotoPoint = 12; continue gotoNext;}
                case 'a':    {gotoPoint = 44; continue gotoNext;}
                default:    {gotoPoint = 4; continue gotoNext;}
                }
            case 4:
                {   return Parser.taguri(YAML.DOMAIN, type_id); }
            case 5:
                yych = data[(marker = ++cursor)];
                switch (yych) {
                case ',':
                case '.':
                case '/':
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                case 'A':
                case 'B':
                case 'C':
                case 'D':
                case 'E':
                case 'F':
                case 'G':
                case 'H':
                case 'I':
                case 'J':
                case 'K':
                case 'L':
                case 'M':
                case 'N':
                case 'O':
                case 'P':
                case 'Q':
                case 'R':
                case 'S':
                case 'T':
                case 'U':
                case 'V':
                case 'W':
                case 'X':
                case 'Y':
                case 'Z':
                case '_':
                case 'a':
                case 'b':
                case 'c':
                case 'd':
                case 'e':
                case 'f':
                case 'g':
                case 'h':
                case 'i':
                case 'j':
                case 'k':
                case 'l':
                case 'm':
                case 'n':
                case 'o':
                case 'p':
                case 'q':
                case 'r':
                case 's':
                case 't':
                case 'u':
                case 'v':
                case 'w':
                case 'x':
                case 'y':
                case 'z':    {gotoPoint = 13; continue gotoNext;}
                case '-':    {gotoPoint = 34; continue gotoNext;}
                default:    {gotoPoint = 4; continue gotoNext;}
                }
            case 6:
                ++cursor;
                {   return Parser.xprivate(type_id.substring(1)); }
            case 8:
                yych = data[(marker = ++cursor)];
                switch (yych) {
                case ',':    {gotoPoint = 14; continue gotoNext;}
                case '-':    {gotoPoint = 10; continue gotoNext;}
                case '.':    {gotoPoint = 15; continue gotoNext;}
                case '/':    {gotoPoint = 16; continue gotoNext;}
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                case 'A':
                case 'B':
                case 'C':
                case 'D':
                case 'E':
                case 'F':
                case 'G':
                case 'H':
                case 'I':
                case 'J':
                case 'K':
                case 'L':
                case 'M':
                case 'N':
                case 'O':
                case 'P':
                case 'Q':
                case 'R':
                case 'S':
                case 'T':
                case 'U':
                case 'V':
                case 'W':
                case 'X':
                case 'Y':
                case 'Z':
                case '_':
                case 'a':
                case 'b':
                case 'c':
                case 'd':
                case 'e':
                case 'f':
                case 'g':
                case 'h':
                case 'i':
                case 'j':
                case 'k':
                case 'l':
                case 'm':
                case 'n':
                case 'o':
                case 'p':
                case 'q':
                case 'r':
                case 's':
                case 't':
                case 'u':
                case 'v':
                case 'w':
                case 'x':
                case 'y':
                case 'z':    {gotoPoint = 12; continue gotoNext;}
                default:    {gotoPoint = 4; continue gotoNext;}
                }
            case 9:
                yych = data[++cursor];
                {gotoPoint = 4; continue gotoNext;}
            case 10:
                ++cursor;
                yych = data[cursor];
            case 11:
                switch (yych) {
                case '-':    {gotoPoint = 10; continue gotoNext;}
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                case 'A':
                case 'B':
                case 'C':
                case 'D':
                case 'E':
                case 'F':
                case 'G':
                case 'H':
                case 'I':
                case 'J':
                case 'K':
                case 'L':
                case 'M':
                case 'N':
                case 'O':
                case 'P':
                case 'Q':
                case 'R':
                case 'S':
                case 'T':
                case 'U':
                case 'V':
                case 'W':
                case 'X':
                case 'Y':
                case 'Z':
                case '_':
                case 'a':
                case 'b':
                case 'c':
                case 'd':
                case 'e':
                case 'f':
                case 'g':
                case 'h':
                case 'i':
                case 'j':
                case 'k':
                case 'l':
                case 'm':
                case 'n':
                case 'o':
                case 'p':
                case 'q':
                case 'r':
                case 's':
                case 't':
                case 'u':
                case 'v':
                case 'w':
                case 'x':
                case 'y':
                case 'z':    {gotoPoint = 12; continue gotoNext;}
                default:    {gotoPoint = 2; continue gotoNext;}
                }
            case 12:
                ++cursor;
                yych = data[cursor];
            case 13:
                switch (yych) {
                case ',':    {gotoPoint = 14; continue gotoNext;}
                case '-':    {gotoPoint = 10; continue gotoNext;}
                case '.':    {gotoPoint = 15; continue gotoNext;}
                case '/':    {gotoPoint = 16; continue gotoNext;}
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                case 'A':
                case 'B':
                case 'C':
                case 'D':
                case 'E':
                case 'F':
                case 'G':
                case 'H':
                case 'I':
                case 'J':
                case 'K':
                case 'L':
                case 'M':
                case 'N':
                case 'O':
                case 'P':
                case 'Q':
                case 'R':
                case 'S':
                case 'T':
                case 'U':
                case 'V':
                case 'W':
                case 'X':
                case 'Y':
                case 'Z':
                case '_':
                case 'a':
                case 'b':
                case 'c':
                case 'd':
                case 'e':
                case 'f':
                case 'g':
                case 'h':
                case 'i':
                case 'j':
                case 'k':
                case 'l':
                case 'm':
                case 'n':
                case 'o':
                case 'p':
                case 'q':
                case 'r':
                case 's':
                case 't':
                case 'u':
                case 'v':
                case 'w':
                case 'x':
                case 'y':
                case 'z':    {gotoPoint = 12; continue gotoNext;}
                default:    {gotoPoint = 2; continue gotoNext;}
                }
            case 14:
                yych = data[++cursor];
                switch (yych) {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':    {gotoPoint = 22; continue gotoNext;}
                default:    {gotoPoint = 2; continue gotoNext;}
                }
            case 15:
                ++cursor;
                yych = data[cursor];
                switch (yych) {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                case 'A':
                case 'B':
                case 'C':
                case 'D':
                case 'E':
                case 'F':
                case 'G':
                case 'H':
                case 'I':
                case 'J':
                case 'K':
                case 'L':
                case 'M':
                case 'N':
                case 'O':
                case 'P':
                case 'Q':
                case 'R':
                case 'S':
                case 'T':
                case 'U':
                case 'V':
                case 'W':
                case 'X':
                case 'Y':
                case 'Z':
                case '_':
                case 'a':
                case 'b':
                case 'c':
                case 'd':
                case 'e':
                case 'f':
                case 'g':
                case 'h':
                case 'i':
                case 'j':
                case 'k':
                case 'l':
                case 'm':
                case 'n':
                case 'o':
                case 'p':
                case 'q':
                case 'r':
                case 's':
                case 't':
                case 'u':
                case 'v':
                case 'w':
                case 'x':
                case 'y':
                case 'z':    {gotoPoint = 18; continue gotoNext;}
                default:    {gotoPoint = 2; continue gotoNext;}
                }
            case 16:
                ++cursor;
                {   
                    return Parser.taguri(type_id.substring(0, cursor -1) + "." + YAML.DOMAIN, type_id.substring(cursor));
                }
            case 18:
                ++cursor;
                yych = data[cursor];
                switch (yych) {
                case ',':    {gotoPoint = 14; continue gotoNext;}
                case '-':    {gotoPoint = 20; continue gotoNext;}
                case '.':    {gotoPoint = 15; continue gotoNext;}
                case '/':    {gotoPoint = 16; continue gotoNext;}
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                case 'A':
                case 'B':
                case 'C':
                case 'D':
                case 'E':
                case 'F':
                case 'G':
                case 'H':
                case 'I':
                case 'J':
                case 'K':
                case 'L':
                case 'M':
                case 'N':
                case 'O':
                case 'P':
                case 'Q':
                case 'R':
                case 'S':
                case 'T':
                case 'U':
                case 'V':
                case 'W':
                case 'X':
                case 'Y':
                case 'Z':
                case '_':
                case 'a':
                case 'b':
                case 'c':
                case 'd':
                case 'e':
                case 'f':
                case 'g':
                case 'h':
                case 'i':
                case 'j':
                case 'k':
                case 'l':
                case 'm':
                case 'n':
                case 'o':
                case 'p':
                case 'q':
                case 'r':
                case 's':
                case 't':
                case 'u':
                case 'v':
                case 'w':
                case 'x':
                case 'y':
                case 'z':    {gotoPoint = 18; continue gotoNext;}
                default:    {gotoPoint = 2; continue gotoNext;}
                }
            case 20:
                ++cursor;
                yych = data[cursor];
                switch (yych) {
                case '-':    {gotoPoint = 20; continue gotoNext;}
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                case 'A':
                case 'B':
                case 'C':
                case 'D':
                case 'E':
                case 'F':
                case 'G':
                case 'H':
                case 'I':
                case 'J':
                case 'K':
                case 'L':
                case 'M':
                case 'N':
                case 'O':
                case 'P':
                case 'Q':
                case 'R':
                case 'S':
                case 'T':
                case 'U':
                case 'V':
                case 'W':
                case 'X':
                case 'Y':
                case 'Z':
                case '_':
                case 'a':
                case 'b':
                case 'c':
                case 'd':
                case 'e':
                case 'f':
                case 'g':
                case 'h':
                case 'i':
                case 'j':
                case 'k':
                case 'l':
                case 'm':
                case 'n':
                case 'o':
                case 'p':
                case 'q':
                case 'r':
                case 's':
                case 't':
                case 'u':
                case 'v':
                case 'w':
                case 'x':
                case 'y':
                case 'z':    {gotoPoint = 18; continue gotoNext;}
                default:    {gotoPoint = 2; continue gotoNext;}
                }
            case 22:
                yych = data[++cursor];
                switch (yych) {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':    {gotoPoint = 23; continue gotoNext;}
                default:    {gotoPoint = 2; continue gotoNext;}
                }
            case 23:
                yych = data[++cursor];
                switch (yych) {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':    {gotoPoint = 24; continue gotoNext;}
                default:    {gotoPoint = 2; continue gotoNext;}
                }
            case 24:
                yych = data[++cursor];
                switch (yych) {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':    {gotoPoint = 25; continue gotoNext;}
                default:    {gotoPoint = 2; continue gotoNext;}
                }
            case 25:
                yych = data[++cursor];
                switch (yych) {
                case '-':    {gotoPoint = 26; continue gotoNext;}
                case '/':    {gotoPoint = 27; continue gotoNext;}
                default:    {gotoPoint = 2; continue gotoNext;}
                }
            case 26:
                yych = data[++cursor];
                switch (yych) {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':    {gotoPoint = 29; continue gotoNext;}
                default:    {gotoPoint = 2; continue gotoNext;}
                }
            case 27:
                ++cursor;
                {   
                               return Parser.taguri(type_id.substring(0, cursor-1), type_id.substring(cursor));
                            }
            case 29:
                yych = data[++cursor];
                switch (yych) {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':    {gotoPoint = 30; continue gotoNext;}
                default:    {gotoPoint = 2; continue gotoNext;}
                }
            case 30:
                yych = data[++cursor];
                switch (yych) {
                case '-':    {gotoPoint = 31; continue gotoNext;}
                case '/':    {gotoPoint = 27; continue gotoNext;}
                default:    {gotoPoint = 2; continue gotoNext;}
                }
            case 31:
                yych = data[++cursor];
                switch (yych) {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':    {gotoPoint = 32; continue gotoNext;}
                default:    {gotoPoint = 2; continue gotoNext;}
                }
            case 32:
                yych = data[++cursor];
                switch (yych) {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':    {gotoPoint = 33; continue gotoNext;}
                default:    {gotoPoint = 2; continue gotoNext;}
                }
            case 33:
                yych = data[++cursor];
                switch (yych) {
                case '/':    {gotoPoint = 27; continue gotoNext;}
                default:    {gotoPoint = 2; continue gotoNext;}
                }
            case 34:
                yych = data[++cursor];
                switch (yych) {
                case 'p':    {gotoPoint = 35; continue gotoNext;}
                default:    {gotoPoint = 11; continue gotoNext;}
                }
            case 35:
                yych = data[++cursor];
                switch (yych) {
                case ',':    {gotoPoint = 14; continue gotoNext;}
                case '.':    {gotoPoint = 15; continue gotoNext;}
                case '/':    {gotoPoint = 16; continue gotoNext;}
                case 'r':    {gotoPoint = 36; continue gotoNext;}
                default:    {gotoPoint = 11; continue gotoNext;}
                }
            case 36:
                yych = data[++cursor];
                switch (yych) {
                case ',':    {gotoPoint = 14; continue gotoNext;}
                case '.':    {gotoPoint = 15; continue gotoNext;}
                case '/':    {gotoPoint = 16; continue gotoNext;}
                case 'i':    {gotoPoint = 37; continue gotoNext;}
                default:    {gotoPoint = 11; continue gotoNext;}
                }
            case 37:
                yych = data[++cursor];
                switch (yych) {
                case ',':    {gotoPoint = 14; continue gotoNext;}
                case '.':    {gotoPoint = 15; continue gotoNext;}
                case '/':    {gotoPoint = 16; continue gotoNext;}
                case 'v':    {gotoPoint = 38; continue gotoNext;}
                default:    {gotoPoint = 11; continue gotoNext;}
                }
            case 38:
                yych = data[++cursor];
                switch (yych) {
                case ',':    {gotoPoint = 14; continue gotoNext;}
                case '.':    {gotoPoint = 15; continue gotoNext;}
                case '/':    {gotoPoint = 16; continue gotoNext;}
                case 'a':    {gotoPoint = 39; continue gotoNext;}
                default:    {gotoPoint = 11; continue gotoNext;}
                }
            case 39:
                yych = data[++cursor];
                switch (yych) {
                case ',':    {gotoPoint = 14; continue gotoNext;}
                case '.':    {gotoPoint = 15; continue gotoNext;}
                case '/':    {gotoPoint = 16; continue gotoNext;}
                case 't':    {gotoPoint = 40; continue gotoNext;}
                default:    {gotoPoint = 11; continue gotoNext;}
                }
            case 40:
                yych = data[++cursor];
                switch (yych) {
                case ',':    {gotoPoint = 14; continue gotoNext;}
                case '.':    {gotoPoint = 15; continue gotoNext;}
                case '/':    {gotoPoint = 16; continue gotoNext;}
                case 'e':    {gotoPoint = 41; continue gotoNext;}
                default:    {gotoPoint = 11; continue gotoNext;}
                }
            case 41:
                yych = data[++cursor];
                switch (yych) {
                case ',':    {gotoPoint = 14; continue gotoNext;}
                case '.':    {gotoPoint = 15; continue gotoNext;}
                case '/':    {gotoPoint = 16; continue gotoNext;}
                case ':':    {gotoPoint = 42; continue gotoNext;}
                default:    {gotoPoint = 11; continue gotoNext;}
                }
            case 42:
                ++cursor;
                {   return type_id; }
            case 44:
                yych = data[++cursor];
                switch (yych) {
                case ',':    {gotoPoint = 14; continue gotoNext;}
                case '.':    {gotoPoint = 15; continue gotoNext;}
                case '/':    {gotoPoint = 16; continue gotoNext;}
                case 'g':    {gotoPoint = 45; continue gotoNext;}
                default:    {gotoPoint = 11; continue gotoNext;}
                }
            case 45:
                yych = data[++cursor];
                switch (yych) {
                case ',':    {gotoPoint = 14; continue gotoNext;}
                case '.':    {gotoPoint = 15; continue gotoNext;}
                case '/':    {gotoPoint = 16; continue gotoNext;}
                case ':':    {gotoPoint = 46; continue gotoNext;}
                default:    {gotoPoint = 11; continue gotoNext;}
                }
            case 46:
                yych = data[++cursor];
                switch (yych) {
                case ',':
                case '-':
                case '.':    {gotoPoint = 2; continue gotoNext;}
                default:    {gotoPoint = 48; continue gotoNext;}
                }
            case 47:
                ++cursor;
                yych = data[cursor];
            case 48:
                switch (yych) {
                case ',':    {gotoPoint = 51; continue gotoNext;}
                case '-':    {gotoPoint = 49; continue gotoNext;}
                case '.':    {gotoPoint = 52; continue gotoNext;}
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                case 'A':
                case 'B':
                case 'C':
                case 'D':
                case 'E':
                case 'F':
                case 'G':
                case 'H':
                case 'I':
                case 'J':
                case 'K':
                case 'L':
                case 'M':
                case 'N':
                case 'O':
                case 'P':
                case 'Q':
                case 'R':
                case 'S':
                case 'T':
                case 'U':
                case 'V':
                case 'W':
                case 'X':
                case 'Y':
                case 'Z':
                case '_':
                case 'a':
                case 'b':
                case 'c':
                case 'd':
                case 'e':
                case 'f':
                case 'g':
                case 'h':
                case 'i':
                case 'j':
                case 'k':
                case 'l':
                case 'm':
                case 'n':
                case 'o':
                case 'p':
                case 'q':
                case 'r':
                case 's':
                case 't':
                case 'u':
                case 'v':
                case 'w':
                case 'x':
                case 'y':
                case 'z':    {gotoPoint = 47; continue gotoNext;}
                default:    {gotoPoint = 2; continue gotoNext;}
                }
            case 49:
                ++cursor;
                yych = data[cursor];
                switch (yych) {
                case '-':    {gotoPoint = 49; continue gotoNext;}
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                case 'A':
                case 'B':
                case 'C':
                case 'D':
                case 'E':
                case 'F':
                case 'G':
                case 'H':
                case 'I':
                case 'J':
                case 'K':
                case 'L':
                case 'M':
                case 'N':
                case 'O':
                case 'P':
                case 'Q':
                case 'R':
                case 'S':
                case 'T':
                case 'U':
                case 'V':
                case 'W':
                case 'X':
                case 'Y':
                case 'Z':
                case '_':
                case 'a':
                case 'b':
                case 'c':
                case 'd':
                case 'e':
                case 'f':
                case 'g':
                case 'h':
                case 'i':
                case 'j':
                case 'k':
                case 'l':
                case 'm':
                case 'n':
                case 'o':
                case 'p':
                case 'q':
                case 'r':
                case 's':
                case 't':
                case 'u':
                case 'v':
                case 'w':
                case 'x':
                case 'y':
                case 'z':    {gotoPoint = 47; continue gotoNext;}
                default:    {gotoPoint = 2; continue gotoNext;}
                }
            case 51:
                yych = data[++cursor];
                switch (yych) {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':    {gotoPoint = 57; continue gotoNext;}
                default:    {gotoPoint = 2; continue gotoNext;}
                }
            case 52:
                ++cursor;
                yych = data[cursor];
                switch (yych) {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                case 'A':
                case 'B':
                case 'C':
                case 'D':
                case 'E':
                case 'F':
                case 'G':
                case 'H':
                case 'I':
                case 'J':
                case 'K':
                case 'L':
                case 'M':
                case 'N':
                case 'O':
                case 'P':
                case 'Q':
                case 'R':
                case 'S':
                case 'T':
                case 'U':
                case 'V':
                case 'W':
                case 'X':
                case 'Y':
                case 'Z':
                case '_':
                case 'a':
                case 'b':
                case 'c':
                case 'd':
                case 'e':
                case 'f':
                case 'g':
                case 'h':
                case 'i':
                case 'j':
                case 'k':
                case 'l':
                case 'm':
                case 'n':
                case 'o':
                case 'p':
                case 'q':
                case 'r':
                case 's':
                case 't':
                case 'u':
                case 'v':
                case 'w':
                case 'x':
                case 'y':
                case 'z':    {gotoPoint = 53; continue gotoNext;}
                default:    {gotoPoint = 2; continue gotoNext;}
                }
            case 53:
                ++cursor;
                yych = data[cursor];
                switch (yych) {
                case ',':    {gotoPoint = 51; continue gotoNext;}
                case '-':    {gotoPoint = 55; continue gotoNext;}
                case '.':    {gotoPoint = 52; continue gotoNext;}
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                case 'A':
                case 'B':
                case 'C':
                case 'D':
                case 'E':
                case 'F':
                case 'G':
                case 'H':
                case 'I':
                case 'J':
                case 'K':
                case 'L':
                case 'M':
                case 'N':
                case 'O':
                case 'P':
                case 'Q':
                case 'R':
                case 'S':
                case 'T':
                case 'U':
                case 'V':
                case 'W':
                case 'X':
                case 'Y':
                case 'Z':
                case '_':
                case 'a':
                case 'b':
                case 'c':
                case 'd':
                case 'e':
                case 'f':
                case 'g':
                case 'h':
                case 'i':
                case 'j':
                case 'k':
                case 'l':
                case 'm':
                case 'n':
                case 'o':
                case 'p':
                case 'q':
                case 'r':
                case 's':
                case 't':
                case 'u':
                case 'v':
                case 'w':
                case 'x':
                case 'y':
                case 'z':    {gotoPoint = 53; continue gotoNext;}
                default:    {gotoPoint = 2; continue gotoNext;}
                }
            case 55:
                ++cursor;
                yych = data[cursor];
                switch (yych) {
                case '-':    {gotoPoint = 55; continue gotoNext;}
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                case 'A':
                case 'B':
                case 'C':
                case 'D':
                case 'E':
                case 'F':
                case 'G':
                case 'H':
                case 'I':
                case 'J':
                case 'K':
                case 'L':
                case 'M':
                case 'N':
                case 'O':
                case 'P':
                case 'Q':
                case 'R':
                case 'S':
                case 'T':
                case 'U':
                case 'V':
                case 'W':
                case 'X':
                case 'Y':
                case 'Z':
                case '_':
                case 'a':
                case 'b':
                case 'c':
                case 'd':
                case 'e':
                case 'f':
                case 'g':
                case 'h':
                case 'i':
                case 'j':
                case 'k':
                case 'l':
                case 'm':
                case 'n':
                case 'o':
                case 'p':
                case 'q':
                case 'r':
                case 's':
                case 't':
                case 'u':
                case 'v':
                case 'w':
                case 'x':
                case 'y':
                case 'z':    {gotoPoint = 53; continue gotoNext;}
                default:    {gotoPoint = 2; continue gotoNext;}
                }
            case 57:
                yych = data[++cursor];
                switch (yych) {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':    {gotoPoint = 58; continue gotoNext;}
                default:    {gotoPoint = 2; continue gotoNext;}
                }
            case 58:
                yych = data[++cursor];
                switch (yych) {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':    {gotoPoint = 59; continue gotoNext;}
                default:    {gotoPoint = 2; continue gotoNext;}
                }
            case 59:
                yych = data[++cursor];
                switch (yych) {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':    {gotoPoint = 60; continue gotoNext;}
                default:    {gotoPoint = 2; continue gotoNext;}
                }
            case 60:
                yych = data[++cursor];
                switch (yych) {
                case '-':    {gotoPoint = 61; continue gotoNext;}
                case ':':    {gotoPoint = 62; continue gotoNext;}
                default:    {gotoPoint = 2; continue gotoNext;}
                }
            case 61:
                yych = data[++cursor];
                switch (yych) {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':    {gotoPoint = 64; continue gotoNext;}
                default:    {gotoPoint = 2; continue gotoNext;}
                }
            case 62:
                ++cursor;
                {   return type_id; }
            case 64:
                yych = data[++cursor];
                switch (yych) {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':    {gotoPoint = 65; continue gotoNext;}
                default:    {gotoPoint = 2; continue gotoNext;}
                }
            case 65:
                yych = data[++cursor];
                switch (yych) {
                case '-':    {gotoPoint = 66; continue gotoNext;}
                case ':':    {gotoPoint = 62; continue gotoNext;}
                default:    {gotoPoint = 2; continue gotoNext;}
                }
            case 66:
                yych = data[++cursor];
                switch (yych) {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':    {gotoPoint = 67; continue gotoNext;}
                default:    {gotoPoint = 2; continue gotoNext;}
                }
            case 67:
                yych = data[++cursor];
                switch (yych) {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':    {gotoPoint = 68; continue gotoNext;}
                default:    {gotoPoint = 2; continue gotoNext;}
                }
            case 68:
                ++cursor;
                switch ((yych = data[cursor])) {
                case ':':    {gotoPoint = 62; continue gotoNext;}
                default:    {gotoPoint = 2; continue gotoNext;}
                }
            }
        }

        return null;
    }
}
